# Generated by Django 4.1.7 on 2023-03-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_sep', models.CharField(choices=[(',', ','), (';', ';')], max_length=10)),
                ('string_character', models.CharField(choices=[("'", "'"), ('"', '"')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('Full name', 'Full name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Job', 'Job'), ('Date', 'Date')], max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schemamodel')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='media/files/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schemamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
